# Note that no project substructure is specified by
# here. Cargo will figure it all out from the file and path
# names.

[package]
name = "multibin"
version = "0.1.0"
authors = ["Bart Massey <bart@cs.pdx.edu>"]
edition = "2018"

[dependencies]
